### ISSUE TITLE
discussion rt-config.php 

### ISSUE THREAD

**Issue by radhe** [rtCamp/wordpress-skeleton#6]
We need clarity on how to manage this rt-config.php

It should not be open to all https://rtmedia.io/wp-content/rt-config/rt-config.php

Not sure how VIP manages it https://indianexpress.com/wp-content/vip-config/vip-config.php

Also variable values in the rt-config.php should be stored in GH secrets. 
Not sure how different env should be managed here, Should we have LIVE, TEST and DEV secret variables separately. 
 
https://github.com/rtCamp/wordpress-skeleton/settings/secrets

**Comment by chandrapatel** [comment]
@radhe we can add task in deployer which will move `rt-config/rt-config.php` to `releases` folder similar to `wp-config.php` symlink.

For now, I'm creating PR to add `rt-config/rt-config.php` file.

**Comment by chandrapatel** [comment]
@radhe https://github.com/rtCamp/wordpress-skeleton/pull/7

**Comment by chandrapatel** [comment]
@radhe Either we can do symlink of `rt-config.php` file as I mentioned in https://github.com/rtCamp/wordpress-skeleton/issues/6#issuecomment-495532190. OR we can add 404 rule at Nginx level (Not sure if possible).

>Also variable values in the rt-config.php should be stored in GH secrets.
Not sure how different env should be managed here, Should we have LIVE, TEST and DEV secret variables separately.

I think we can keep any constant for 3rd party APIs or any code which we need to keep in `wp-config.php` in `rt-config.php` file. Also, we can easily manage constant based on the different environments in PHP.

**Comment by radhe** [comment]
1. API keys will be kept in Github secrets 
2. rt-config.php will not have any thing to execute or show but we can block it with nginx rule

**Comment by chandrapatel** [comment]
> rt-config.php will not have anything to execute or show but we can block it with Nginx rule

@radhe Okay. Let's do that in existing/future projects. I think we can close this issue now.

**Comment by chandrapatel** [comment]
@radhe Can we close this issue?

**Comment by chandrapatel** [comment]
I'm closing this issue.
